# Generated by Django 2.2.4 on 2019-08-31 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbanProject', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hackerNews',
            new_name='hackerNewsAPI',
        ),
    ]
