# Generated by Django 2.2.4 on 2019-09-01 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbanProject', '0002_auto_20190831_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackernewsapi',
            old_name='aricle_id',
            new_name='article_id',
        ),
    ]
