# Generated by Django 2.2.4 on 2019-09-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanProject', '0003_auto_20190901_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackernewsapi',
            name='article_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='hackernewsapi',
            name='score',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='hackernewsapi',
            name='sentiment',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='hackernewsapi',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='hackernewsapi',
            name='url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='hackernewsapi',
            name='username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
