# Generated by Django 2.2.4 on 2019-09-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanProject', '0004_auto_20190901_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackernewsapi',
            name='article_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hackernewsapi',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hackernewsapi',
            name='sentiment',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hackernewsapi',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hackernewsapi',
            name='url',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hackernewsapi',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
