# Generated by Django 2.2.4 on 2019-09-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanProject', '0005_auto_20190901_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackernewsapi',
            name='article_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
