# Generated by Django 2.2.4 on 2019-09-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanProject', '0006_auto_20190901_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackernewsapi',
            name='id',
        ),
        migrations.AddField(
            model_name='hackernewsapi',
            name='auto_increment_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
